"""Initial migration

Revision ID: 115bcd2e1a38
Revises: 
Create Date: 2025-09-12 16:06:16.479075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115bcd2e1a38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userkey', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('url_hash', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('favicon', sa.String(length=255), nullable=True),
    sa.Column('starred', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), server_default=sa.text('(null)'), nullable=True),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('note', sa.Text(), server_default=sa.text('(null)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publictag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagkey', sa.String(length=255), nullable=False),
    sa.Column('userkey', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(null)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('theme', sa.String(length=20), server_default=sa.text("'green'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('publictag')
    op.drop_table('bookmark')
    # ### end Alembic commands ###
